debug: false

server:
  error:
    whitelabel:
      enabled: false
  max-http-header-size: 8KB
  port: ${BE_SERVER_PORT}

spring:
  datasource:
    url: ${BE_DB_URL}
    username: ${BE_DB_USER}
    password: ${BE_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    locations: "classpath:db/migration/{vendor}"
    baselineOnMigrate: true
